version: "3.1"
services:
    www:
        build: .
        ports: 
            - "80:80"
        volumes:
            - D:/work/tsmg/_source_v3/tsmg_traffic_cms_v2:/var/www/tsmg_traffic_cms_v2
            - ./conf/000-default.conf:/etc/apache2/sites-available/000-default.conf
        environment:
            VIRTUAL_HOST: traffic.local
        links:
            - db
        networks:
            - default
    db:
        image: mysql:5.7
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: dev
            MYSQL_PASSWORD: dev1234
            MYSQL_ROOT_PASSWORD: root1234 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - ./mysql_data:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8090:80
        environment:
            MYSQL_USER: dev
            MYSQL_PASSWORD: dev1234
            MYSQL_ROOT_PASSWORD: root1234 

